### ISSUE TITLE
blank line when using `add_section`

### ISSUE THREAD

**Issue by sgbaird** [marcelotrevisani/souschef#47]
Was asked to fix this for future recipes on `conda-forge`.

https://github.com/conda-forge/staged-recipes/pull/19083#issuecomment-1140258048

```yaml
...
build:
  number: 0
  entry_points:
    - xtal2png = xtal2png.core:run
  script: {{ PYTHON }} -m pip install . -vv

  noarch: python
requirements:
...
```
should be:
```yaml
...
build:
  number: 0
  entry_points:
    - xtal2png = xtal2png.core:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
...
```
Rn looking into how to fix this without any changes on `conda-souschef` side.

**Comment by sgbaird** [comment]
I can confirm that this seems to have been fixed (see [`run_grayskull.py`](https://github.com/sparks-baird/mp-time-split/blob/main/scripts/run_grayskull.py)):
```yaml
{% set name = "mp_time_split" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  entry_points:
    - mp_time_split = mp_time_split.core:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-time-split-{{ version }}.tar.gz
  sha256: a7edb6294d8fd11bbdefe7a73f6a2d0b9eb57cfdeb3884d28843b4791ffce027

requirements:
  host:
    - pip
    - setuptools-scm
    - python >=3.6
  run:
    - matminer
    - pymatgen
    - scikit-learn

    - python >=3.6
    - importlib-metadata
test:
  imports:
    - mp_time_split
  commands:
    - pip check
    - mp_time_split --help
  requires:
    - pip

about:
  home: https://github.com/sparks-baird/mp-time-split
  summary: Use Materials Project time-splits for generative modeling benchmarking.
  dev_url: https://github.com/sparks-baird/mp-time-split
  license: MIT
  license_file: LICENSE.txt
  doc_url: mp-time-split.readthedocs.io

extra:
  recipe-maintainers:
    - sgbaird
```
Thanks again!
